config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :project_steps, only: [:edit, :update]
  end
  resources :projects do
    resources :project_steps, only: [:edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/project/basic_info.rb
class Project::BasicInfo < Project
  # Include step validations here

  # Include step after_initialize attribute default settings here

  # Include step after_save changes here

  def editable?
    true
  end
end

app/models/project/file_uploads.rb
class Project::FileUploads < Project
  # Include step validations here

  # Include step after_initialize attribute default settings here

  # Include step after_save changes here

  def editable?
    true
  end
end

app/models/project/preview.rb
class Project::Preview < Project
  # Include step validations here

  # Include step after_initialize attribute default settings here

  # Include step after_save changes here

  def editable?
    true
  end
end

app/models/project/project_detail.rb
class Project::ProjectDetail < Project
  # Include step validations here

  # Include step after_initialize attribute default settings here

  # Include step after_save changes here

  def editable?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/project_steps_controller.rb
class ProjectStepsController < ApplicationController
  include ProjectStepsHelper
  helper ProjectStepsHelper
  before_action :load_project

  def edit
    if project_step_model.editable?
      if step.present?
        render step
      else
        render "#{Rails.root.to_s}/public/404.html", :layout => false, :status => 404
      end
    else
      redirect_to :back, :alert => I18n.t("project.#{@project.status}_editable_error")
    end
  end

  def update
    if project_step_model.update_attributes(project_params || {})
      if next_step && params[:commit].downcase.include?('next')
        redirect_to edit_project_project_step_path(project_step_model, next_step)
      else
        redirect_to project_path(@project)
      end
    else
      render step, :error => "Please complete all required fields"
    end
  end

  private

  def load_project
    @project = project_step_model
  end

  def project_params
    params.require(:project).permit("name", "description", "start_date", "delivery_date")
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectStepsHelper
  helper ProjectStepsHelper

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save(validation: false)
        format.html { redirect_to edit_project_project_step_path(@project, ProjectStepsHelper::STEPS.first) }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      return {} unless params[:project].present?
      params.require(:project).permit(:name, :description, :start_date, :delivery_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_steps_helper.rb
module ProjectStepsHelper
  STEPS = %w(basic_info project_detail file_uploads preview)

  def project_step_model
    project_class = "Project::#{step.camelcase}".constantize rescue Project
    @project ||= project_class.find(params[:project_id])
  end

  def step
    # Filter for security reasons
    @step ||= STEPS.find {|a_step| a_step == params[:id].to_s.downcase}
  end
  alias current_step step

  def previous_step
    current_step_index = STEPS.index(step)
    previous_step_index = current_step_index-1
    previous_step_index < 0 ? nil : STEPS[previous_step_index]
  end

  def next_step
    current_step_index = STEPS.index(step)
    STEPS[current_step_index+1]
  end

  
  
  def edit_first_step_path
    edit_project_step_model_path(STEPS.first)
  end

  def edit_previous_step_path
    edit_project_step_model_path(previous_step)
  end

  def edit_next_step_path
    edit_project_step_model_path(next_step)
  end

  def edit_last_step_path
    edit_project_step_model_path(STEPS.last)
  end

  def edit_current_step_path
    edit_project_step_model_path(step)
  end

  def edit_project_step_model_path(step)
    edit_project_project_step_path(project_step_model, step)
  end
  
  def first_step_path
    project_step_model_path(STEPS.first)
  end

  def previous_step_path
    project_step_model_path(previous_step)
  end

  def next_step_path
    project_step_model_path(next_step)
  end

  def last_step_path
    project_step_model_path(STEPS.last)
  end

  def current_step_path
    project_step_model_path(step)
  end

  def project_step_model_path(step)
    project_project_step_path(project_step_model, step)
  end
  
  
  
  def edit_first_step_url
    edit_project_step_model_url(STEPS.first)
  end

  def edit_previous_step_url
    edit_project_step_model_url(previous_step)
  end

  def edit_next_step_url
    edit_project_step_model_url(next_step)
  end

  def edit_last_step_url
    edit_project_step_model_url(STEPS.last)
  end

  def edit_current_step_url
    edit_project_step_model_url(step)
  end

  def edit_project_step_model_url(step)
    edit_project_project_step_url(project_step_model, step)
  end
  
  def first_step_url
    project_step_model_url(STEPS.first)
  end

  def previous_step_url
    project_step_model_url(previous_step)
  end

  def next_step_url
    project_step_model_url(next_step)
  end

  def last_step_url
    project_step_model_url(STEPS.last)
  end

  def current_step_url
    project_step_model_url(step)
  end

  def project_step_model_url(step)
    project_project_step_url(project_step_model, step)
  end
  
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestWizard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/project_steps/_step_breadcrumb.html.erb
<div class="step_breadcrumbs">
  <% ProjectStepsHelper::STEPS.each_with_index do |breadcrumb_step, index| %>
    <%= link_to edit_project_step_model_path(breadcrumb_step), class: "step_breadcrumb #{"selected_step" if breadcrumb_step == current_step}" do %>
      <div class="step_number"><%= step_number = index + 1 %></div>
      <div class="step_name"><%= breadcrumb_step.humanize %></div>
    <% end %>
  <% end %>
</div>

app/views/project_steps/_step_navigation.html.erb
<ul>
  <% if previous_step.present? %>
    <li><%= link_to "Previous step", edit_previous_step_path %></li>
  <% end %>
  <li><%= f.submit next_step.present? ? "next" : "finish" %></li>
</ul>

app/views/project_steps/basic_info.html.erb
<h1>Project wizard</h1>
<%= render 'step_breadcrumb' %>
<h2>Step: Basic info</h2>
<%= form_for project_step_model, :url => current_step_path, :as => :project do |f| %>
  <%# TODO limit to fields of this particular step %>
    <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :delivery_date %>
    <%= form.date_select :delivery_date %>
  </div>


  <%= render 'step_navigation', f: f %>
<% end %>

app/views/project_steps/file_uploads.html.erb
<h1>Project wizard</h1>
<%= render 'step_breadcrumb' %>
<h2>Step: File uploads</h2>
<%= form_for project_step_model, :url => current_step_path, :as => :project do |f| %>
  <%# TODO limit to fields of this particular step %>
    <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :delivery_date %>
    <%= form.date_select :delivery_date %>
  </div>


  <%= render 'step_navigation', f: f %>
<% end %>

app/views/project_steps/preview.html.erb
<h1>Project wizard</h1>
<%= render 'step_breadcrumb' %>
<h2>Step: Preview</h2>
<%= form_for project_step_model, :url => current_step_path, :as => :project do |f| %>
  <%# TODO limit to fields of this particular step %>
    <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :delivery_date %>
    <%= form.date_select :delivery_date %>
  </div>


  <%= render 'step_navigation', f: f %>
<% end %>

app/views/project_steps/project_detail.html.erb
<h1>Project wizard</h1>
<%= render 'step_breadcrumb' %>
<h2>Step: Project detail</h2>
<%= form_for project_step_model, :url => current_step_path, :as => :project do |f| %>
  <%# TODO limit to fields of this particular step %>
    <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :delivery_date %>
    <%= form.date_select :delivery_date %>
  </div>


  <%= render 'step_navigation', f: f %>
<% end %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :delivery_date %>
    <%= form.date_select :delivery_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start date</th>
      <th>Delivery date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.start_date %></td>
        <td><%= project.delivery_date %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', projects_path, method: :post %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>Delivery date:</strong>
  <%= @project.delivery_date %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>